apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/zregvart/devfile-sample-code-with-quarkus?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "100"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: devfile-sample-code-with-quarkus
    appstudio.openshift.io/component: devfile-sample-code-with-quarkus
    pipelines.appstudio.openshift.io/type: build
  name: devfile-sample-code-with-quarkus-on-push
  namespace: zregvart-tenant
spec:
  params:
    - name: dockerfile
      value: src/main/docker/Dockerfile.jvm.staged
    - name: git-url
      value: https://github.com/zregvart/devfile-sample-code-with-quarkus.git
    - name: output-image
      value: quay.io/redhat-user-workloads-stage/zregvart-tenant/devfile-sample-code-with-quarkus/devfile-sample-code-with-quarkus:{{revision}}
    - name: path-context
      value: .
    - name: revision
      value: '{{revision}}'
    - name: hermetic
      value: 'true'
  pipelineRef:
    params:
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/pipeline-java-builder:devel
      - name: name
        value: java-builder
      - name: kind
        value: pipeline
    resolver: bundles
  taskRunTemplate:
    podTemplate:
      env:
        - name: DEBUG
          value: '1'
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
